binary-ghc-args:
- -O
- -threaded
module-template: ! 'module MODULE_NAME where

'
extensions: {}
environment: ghc-7.8-stable-14.09
auto-hidden: []
cabal-file: project.cabal
version: 1
extra-packages: https://hackage.haskell.org/package/markov-chain-0.0.3.3/markov-chain-0.0.3.3.tar.gz
ghc-args: []
excluded-modules: []
